# (실습) 넘파이 어레이

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

## numpy 모듈

**문제 1**

아래 코드를 설명하라.

In [1]:
import numpy as np

`코드설명`: 넘파이 기본 모듈 임폴트

아래 코드는 수정하지 마세요!!!

In [2]:
np.__version__

'1.26.4'

**문제 2**

아래 코드의 기능을 설명하라

In [ ]:
np.random.seed(42)

`코드설명`: 42까지의 랜덤시드 생성

**문제 3**

부동소수점으로 구성된 어레이의 항목은 기본적으로 소수점 이하 8자리까지 출력한다.

In [3]:
Z = np.random.random((40,40))
Z

array([[0.14212133, 0.45513806, 0.57902406, ..., 0.17524441, 0.32361802,
        0.57091341],
       [0.95246032, 0.07265213, 0.14121553, ..., 0.1388551 , 0.69755234,
        0.17828653],
       [0.34083857, 0.19982505, 0.84158356, ..., 0.19831164, 0.78075047,
        0.77271555],
       ...,
       [0.04676722, 0.08464179, 0.14928981, ..., 0.61288741, 0.13461771,
        0.45002274],
       [0.87275801, 0.59809252, 0.97613938, ..., 0.34774266, 0.55721059,
        0.67063702],
       [0.48919849, 0.99104513, 0.47476002, ..., 0.09389428, 0.6465654 ,
        0.23629007]])

`np.set_printoptions()` 의 기능을 다음 두 개의 예를 이용하여 설명하라.

In [4]:
np.set_printoptions(precision=4)

In [5]:
Z

array([[0.1421, 0.4551, 0.579 , ..., 0.1752, 0.3236, 0.5709],
       [0.9525, 0.0727, 0.1412, ..., 0.1389, 0.6976, 0.1783],
       [0.3408, 0.1998, 0.8416, ..., 0.1983, 0.7808, 0.7727],
       ...,
       [0.0468, 0.0846, 0.1493, ..., 0.6129, 0.1346, 0.45  ],
       [0.8728, 0.5981, 0.9761, ..., 0.3477, 0.5572, 0.6706],
       [0.4892, 0.991 , 0.4748, ..., 0.0939, 0.6466, 0.2363]])

In [6]:
np.set_printoptions(precision=6)

In [7]:
Z

array([[0.142121, 0.455138, 0.579024, ..., 0.175244, 0.323618, 0.570913],
       [0.95246 , 0.072652, 0.141216, ..., 0.138855, 0.697552, 0.178287],
       [0.340839, 0.199825, 0.841584, ..., 0.198312, 0.78075 , 0.772716],
       ...,
       [0.046767, 0.084642, 0.14929 , ..., 0.612887, 0.134618, 0.450023],
       [0.872758, 0.598093, 0.976139, ..., 0.347743, 0.557211, 0.670637],
       [0.489198, 0.991045, 0.47476 , ..., 0.093894, 0.646565, 0.23629 ]])

`코드설명`: 어레이에 포함된 부동소수점들의 표현 정확도 지정

아래 코드는 기본 옵션값으로 되돌린다. 수정하지 마세요.

In [8]:
np.set_printoptions(precision=8)

## 1차원 어레이

**문제 1**

크기가 10이고 모든 항목이 0인 1차원 어레이를
변수 `Z`가 가리키도록 하라.
단, `np.zeros()` 함수를 반드시 이용한다.

In [9]:
# None을 적절한 표현식으로 대체하라.
Z = np.zeros(10)

아래 코드는 수정하지 마세요!!!

In [10]:
assert (Z == np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 10에서 49까지의 정수 중에서 짝수로만 구성된 1차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수를 반드시 이용한다.

In [15]:
# None을 적절한 표현식으로 대체하라.
Z = np.arange(10, 49 ,2)

아래 코드는 수정하지 마세요!!!

In [16]:
assert (Z == np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
                        44, 46, 48])).all()

**문제 3**

변수 `Z`가 아래와 같이 선언되었다.

In [17]:
Z = np.array([2, 3, 1, 0, 4])
Z

array([2, 3, 1, 0, 4])

변수 `Z`의 항목을 정렬하라.
단, sort() 메서드를 활용한다.

In [18]:
# None을 적절한 표현식으로 대체하라.
Z.sort()

아래 코드는 수정하지 마세요!!!

In [19]:
assert (Z == np.arange(5)).all()

**문제 4**

변수 `Z`가 크기 30이며 무작위로 생성된 1차원 어레이를 가리키도록 하라.
또한 포함된 항목들의 평균값을 계산하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
`np.random.random()` 함수, `mean()` 어레이 메서드를 반드시 이용한다.

In [20]:
# None을 적절한 표현식으로 대체하라.
Z = np.random.random(30)
Z_mean = Z.mean()

아래 코드는 수정하지 마세요!!!

In [21]:
assert (Z.shape == (30,))
print(f"1차원 어레이 평균값: {Z_mean}")

1차원 어레이 평균값: 0.500795179183734


**문제 5**

1차원 어레이가 다음과 같이 주어졌다.

In [22]:
Z = np.arange(1, 4)

(1) 아래 표현식의 계산 결과를 설명하라.

In [23]:
Z*Z

array([1, 4, 9])

`코드설명`: array([1, 2, 3]) * array([1, 2, 3]) = array([1, 4, 9])

(2) 아래 표현식의 계산 결과를 설명하라.

In [24]:
Z**Z

array([ 1,  4, 27])



`코드설명`: 제곱근

(3) 아래 표현식의 계산 결과를 설명하라.

In [25]:
Z < -Z

array([False, False, False])

`코드설명`: array([1, 2, 3]) < array([-1, -2, -3]) = array([False, False, False]

(4) 아래 표현식의 계산 결과를 설명하라.

In [26]:
Z/1/1

array([1., 2., 3.])

`코드설명`: (array([1, 2, 3]) / 1) /1 #동일값 반환

**문제 6**

변수 `Z`가 아래 모양의 어레이를 가리키도록 하라.
단, `np.linspace()` 함수와 `endpoint` 키워드 인자를 이용한다.

```
[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

In [32]:
# None을 적절한 표현식으로 대체하라.
Z = np.linspace(0, 1, 10, endpoint=False)

아래 코드는 수정하지 마세요!!!

In [33]:
assert np.isclose(Z, np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])).all()

**문제 7**

아래 코드의 실행결과를 설명하라.

In [37]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
print(Z.size)
print(Z.itemsize)

800 bytes
100
8


`코드설명`: 0이 10개로 이루어진 튜플 10개
- Z.size는 10*10=100개
- Z.item은 Z = np.zeros((10,10))이 float64 형 데이터 타입이라 8바이트

**문제 8**

다음 리스트에서 0이 아닌 항목들의 인덱스로 구성된 어레이를 한줄 코드로 생성하라.
단. `np.nonzero()` 함수를 활용한다.

In [38]:
Z = [1, 2, 0, 0, 4, 0]

In [39]:
# None을 적절한 표현식으로 대체하라.

non_zeros = np.nonzero(Z)

np.nonzero(Z) #튜플 순서대로 각 배열의 인덱스를 읽음

아래 코드는 수정하지 마세요!!!

In [40]:
assert (non_zeros == np.array([0, 1, 4])).all()

**문제 9**

두 개의 1차원 어레이가 다음과 같이 주어졌다.

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2

아래 코드의 실행 결과를 설명하라.

In [ ]:
(A+B)*(-A/2)

`코드설명`:

In [ ]:
np.add(A,B,out=B)

`코드설명`:

In [ ]:
np.divide(A,2,out=A)

`코드설명`:

In [ ]:
np.negative(A,out=A)

`코드설명`:

In [ ]:
np.multiply(A,B,out=A)

`코드설명`:

## 2차원 어레이

**문제 1**

변수 `Z`가 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (5, 5))
assert (Z.dtype == np.float64)

**문제 2**

변수 `Z`가 0에서 8까지의 정수로 이루어진 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `reshape()` 어레이 메서드를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])).all()

**문제 3**

변수 `Z`가 (3, 3) 모양의 2차원 어레이를 가리키도록 하라.
단, 2차원 어레이의 대각선 상은 1이고 나머지는 0이어야 한다.
또한 `np.eye()` 함수를 반드시 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all

**문제 4**

변수 `Z`가 아래와 같은 (5,5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.arange()` 함수와 `np.diag()` 함수의 `k` 키워드 인자를 반드시 활용한다.

```
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 0, 0, 0, 0],
                        [1, 0, 0, 0, 0],
                        [0, 2, 0, 0, 0],
                        [0, 0, 3, 0, 0],
                        [0, 0, 0, 4, 0]])).all()

**문제 5**

변수 `Z`가 아래와 같은 (5, 5) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수, `np.arange()` 함수, 2차원 어레이 덧셈을 이용한다.

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.],
                        [0., 1., 2., 3., 4.]])).all()

**문제 6**

아래 3x3 단위 행렬에 해당하는 2차원 어레이를 한줄 코드로 생성하라.
단, `np.eye()` 함수를 이용한다.

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[1., 0., 0.],
                       [0., 1., 0.],
                       [0., 0., 1.]])).all()

**문제 7**

무작위 수로 구성된 (5, 5) 모양의 2차원 어레이가 다음과 같다.

In [ ]:
Z = np.random.random((5, 5))

변수 `Z`가 가리키는 2차원 어레이에 대해 min-max 크기조정(정규화)을 적용하라.

min-max 크기조정(정규화)은 항목의 모든 값을 아래 식을 통해 0과 1 사이의 부동소수점으로 변환한다. $max$와 $min$은 각각 최대 항목과 최소 항목을 가리킨다.

$$
\frac{x-min}{max - min}
$$

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.max() == 1 and Z.min() == 0)

## 3차원 어레이

**문제 1**

(1) 변수 `Z`가 (3, 3, 3) 모양의 3차원 어레이를 가리키도록 하라.
단, 어레이의 항목은 0과 1 사이의 임의의 부동소수점으로 구성되어야 한다.
또한 `np.random.random()` 함수를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z.shape == (3, 3, 3))
assert (Z.dtype == 'f8')

(2) `Z`에 포함된 항목들 중에서 최댓값과 최솟값의 차이를 구하라.
단, `maximum`, `mininum` 두 변수가 각각 최댓값과 최솟값을 가리키도록 하며,
`max()`와 `min()` 어레이 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
maximum = None
minimum = None

아래 코드는 수정하지 마세요!!!

In [ ]:
print(f"최댓값과 최솟값의 차이: {maximum - minimum}")

## `dtype` 종류

**문제 1**

아래 두 코드의 실행결과를 설명하라.

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

`코드설명`:

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

`코드설명`:

**문제 2**

부동소수점으로 구성된 1차원 어레이가 아래와 같이 주어졌다.

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)

변수 `Y`가 변수 `Z`가 가리키는 1차원 어레이의 dtype이 `int32`로 형변환된 1차원 어레이를 가리키도록 하라.
단, `astype()` 메서드를 이용한다.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y.shape == (10,))
assert (Y.dtype == np.int32)

**문제 3**

변수 `Z`가 아래와 같이 무작위로 생성된 길이가 10인 1차원 어레이를 가리킨다.

In [ ]:
Z = np.random.uniform(0,10,10)
Z

(1) 나머지 연산자(`%`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(2) 몫 연산자(`//`)를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(3) 내림 함수 `np.floor()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()

(4) `np.trunc()` 함수를 이용하여 정수로만 구성된 어레이 `Y`를 생성하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.
Y = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Y == Z.astype(np.int32)).all()